on :
  push :
    branches :
      - main
      - master
      - develop


name: "Build & Release"
jobs:
  build:
    name: Build & Release App
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          flutter-version:  '3.7.3'
      - run:  flutter pub get
      # Adding Google Services Json from secrets into android folder
      # Google Services Json is gitignored therefore have to add from github secrets
      # Google Services Json is a file obtained from firebase configurations
      - name: Creating Google Service JSON
        env:
          DATA: ${{ secrets.GOOGLE_SERVICES_JSON }}
        run:  touch /dex_messenger/android/app/google-services.json 
              echo $DATA >> /dex_messenger/android/app/google-services.json
              cat /dex_messenger/android/app/google-services.json
      # - run:  flutter test
      - run:  flutter build apk --release --split-per-abi
      - name: Push to Releases
        uses: ncipollo/release-action@v1
        with:
          artificats: "build/app/outputs/apk/release/*"
          tag: v1.0.${{ github.run_number }}
          token: ${{ secrets.BUILDTOKEN }}